# Publishes mui-country-code-selector package to npm
name: Publish to npm

on:
  # Allows you to run this workflow manually from the Actions tab or using GH CLI
  workflow_dispatch:

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "npm"
  cancel-in-progress: false

jobs:
  # build and publish package to npm
  publish:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - run: npm run install-and-build -w mui-country-code-selector
      - run: npm publish -w mui-country-code-selector
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
