# This workflow will run tests and then publish a package to npm if a release is created.

on:
  push:
    branches:
      - main

name: Release and Publish

env:
  HUSKY: 0

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm ci -w mui-country-code-selector
      - run: npm run test -w mui-country-code-selector

  release:
    needs: [test]
    # permissions for the GITHUB_TOKEN to allow deployment to GitHub Pages
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-22.04
    steps:
      # create a release
      - uses: google-github-actions/release-please-action@a37ac6e4f6449ce8b3f7607e4d97d0146028dc0b # v4.1.0
        id: release
        with:
          # a personal access token (PAT) (with Read and Write access to code/
          # contents and pull requests) is needed for the release-please to be
          # able to trigger another workflow that is run after the pull request
          # is accepted
          token: ${{ secrets.RELEASE_TOKEN }}

      # build and publish package to npm
      - uses: actions/checkout@v4
        if: ${{ contains(steps.release.outputs.paths_released, 'packages') }}
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
        if: ${{ contains(steps.release.outputs.paths_released, 'packages') }}
      - run: npm run install-and-build -w mui-country-code-selector
        if: ${{ contains(steps.release.outputs.paths_released, 'packages') }}
      - run: npm publish -w mui-country-code-selector
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        if: ${{ contains(steps.release.outputs.paths_released, 'packages/mui-country-code-selector') }}

      # build and publish the demo page to GitHub pages
      - run: npm run install-and-build -w demo-page
        if: ${{ contains(steps.release.outputs.paths_released, 'packages/demo-page') }}
      - name: Setup Pages
        uses: actions/configure-pages@v5
        if: ${{ contains(steps.release.outputs.paths_released, 'packages/demo-page') }}
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./packages/demo-page/dist"
        if: ${{ contains(steps.release.outputs.paths_released, 'packages/demo-page') }}
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        if: ${{ contains(steps.release.outputs.paths_released, 'packages/demo-page') }}
